# docker-compose up -d --build

version: '3.8'
services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      local-network: { ipv4_address: 192.168.112.4 }

  pgadmin:
    hostname: pgadmin
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      local-network: { ipv4_address: 192.168.112.20 }

networks:
  local-network:
    ipam:
      config: [{subnet: 192.168.112.0/24}]